language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8
sudo: required

script:
  - git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
  - export SWIFTENV_ROOT=$HOME/.swiftenv
  - export PATH=$SWIFTENV_ROOT/bin:$PATH
  - eval "$(swiftenv init -)"
  - swiftenv install 5.1.3
  - ./gradlew build --scan -s


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/